drivers: input: fingerprint: fpc1020: Fix compilation errors
- Add missing member 'irqf' to 'struct fpc1020_data' which was guarded by 'CONFIG_MACH_XIAOMI_SDM660'.
- Fix undefined reference to 'CONFIG_MACH_XIAOMI_SDM660' macro usage.
- Fix potentially undeclared labels 'free_irq_exit' and 'exit_1' by adjusting preprocessor logic.

Signed-off-by: HeroBuxx <me@herobuxx.me>